services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sandbox-backend:local
    ports:
      - "3000:3000"
    environment:
      ENV_NAME: local
      APP_VERSION: dev
